name: Package and release

on:
  push:
    tags:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Install jUI
        run: git clone https://github.com/jadissa/jUI.git Libs/jUI
      - name: Install 
        run: svn checkout https://repos.wowace.com/wow/libstub/trunk Libs/LibStub
      - name: Debug # just to debug
        run: find .