name: Package and release

on:
  push:
    tags:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        uses: actions/checkout@v4
        with: 
          repository: jadissa/jUI
          path: Libs/jUI/
          uses: Libs/jUI/
      - name: Debug # just to debug
        run: find .