name: Package and release

on:
  push:
    tags:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
      - uses: actions/checkout@vmain
      with: 
        repository: jadissa/jUI
        path: Libs/jUI